name: Publish

on:
  workflow_run:
    workflows: [ci]
    types: [completed]
    branches: [main]

jobs:
  publish:
    runs-on: ubuntu-latest

    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Deno version
        run: deno --version

      - name: Publish package
        run: deno publish
